{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "AdventureWorksDW2019",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "PETER",
            "database": "AdventureWorksDW2019"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "peter;AdventureWorksDW2019",
          "Username": "sa",
          "EncryptConnection": false,
          "PrivacySetting": "Organizational"
        }
      }
    ],
    "tables": [
      {
        "name": "Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "FullDateAlternateKey",
            "formatString": "M/d/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"M/d/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "CalendarYear",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "CalendarQuarter",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "MonthNumberOfYear",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "EnglishMonthName",
            "sortByColumn": "Month Number"
          },
          {
            "type": "calculated",
            "name": "Month Key",
            "dataType": "int64",
            "isDataTypeInferred": false,
            "isHidden": true,
            "expression": " LEFT('Date'[Date Key], 6)",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " LEFT('Date'[Month Name], 3) & \" \" & 'Date'[Year]",
            "sortByColumn": "Month Key"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(AdventureWorksDW2019, #\"Source Query - Date\")",
                "in",
                "    Source"
              ]
            }
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "ProductKey",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "ProductAlternateKey"
          },
          {
            "name": "Product Category Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductCategoryKey",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "dataType": "string",
            "sourceColumn": "EnglishProductCategoryName"
          },
          {
            "name": "Product Sub-Category Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductSubcategoryKey",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Product Sub-Category",
            "dataType": "string",
            "sourceColumn": "EnglishProductSubcategoryName"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "EnglishProductName"
          },
          {
            "name": "List Price - Source",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "ListPrice",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "average",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(AdventureWorksDW2019, #\"Source Query - Product\")",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Avg List Price",
            "expression": " AVERAGE('Product'[List Price - Source])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "Internet Sales",
        "columns": [
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Order Date Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateKey",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Due Date Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DueDateKey",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Date Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ShipDateKey",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Order Number",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber"
          },
          {
            "name": "Order Line Number",
            "dataType": "int64",
            "sourceColumn": "SalesOrderLineNumber",
            "formatString": "0",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity - Source",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderQuantity",
            "formatString": "0",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Amount - Source",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "SalesAmount",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Value.NativeQuery(AdventureWorksDW2019, #\"Source Query - Internet Sales\")",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Orders",
            "expression": " DISTINCTCOUNT('Internet Sales'[Order Number])",
            "formatString": "#,0",
            "detailRowsDefinition": {
              "expression": "DETAILROWS('Internet Sales'[Internet Sales Drillthrough - Date Filter Aware])"
            }
          },
          {
            "name": "Quantity",
            "expression": " SUM('Internet Sales'[Quantity - Source]) ",
            "formatString": "#,0",
            "detailRowsDefinition": {
              "expression": "DETAILROWS('Internet Sales'[Internet Sales Drillthrough - Date Filter Aware])"
            }
          },
          {
            "name": "Sales Amount",
            "expression": " SUM('Internet Sales'[Sales Amount - Source])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "detailRowsDefinition": {
              "expression": "DETAILROWS('Internet Sales'[Internet Sales Drillthrough - Date Filter Aware])"
            },
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Internet Sales Drillthrough - Default",
            "expression": " 1",
            "isHidden": true,
            "detailRowsDefinition": {
              "expression": [
                "SELECTCOLUMNS",
                "(",
                "    'Internet Sales'",
                ",   \"Order Number\", 'Internet Sales'[Order Number]",
                ",   \"Order Line Number\", 'Internet Sales'[Order Line Number]",
                ",   \"Order Date\"",
                ",   DATE",
                "    (",
                "        LEFT('Internet Sales'[Order Date Key], 4)",
                "    ,   MID('Internet Sales'[Order Date Key], 5, 2)",
                "    ,   RIGHT('Internet Sales'[Order Date Key], 2)",
                "    )",
                ",   \"Due Date\"",
                ",   DATE",
                "    (",
                "        LEFT('Internet Sales'[Due Date Key], 4)",
                "    ,   MID('Internet Sales'[Due Date Key], 5, 2)",
                "    ,   RIGHT('Internet Sales'[Due Date Key], 2)",
                "    )",
                ",   \"Ship Date\"",
                ",   DATE",
                "    (",
                "        LEFT('Internet Sales'[Ship Date Key], 4)",
                "    ,   MID('Internet Sales'[Ship Date Key], 5, 2)",
                "    ,   RIGHT('Internet Sales'[Ship Date Key], 2)",
                "    )",
                ",   \"Quantity\", 'Internet Sales'[Quantity - Source]",
                ",   \"Sales Amount\", 'Internet Sales'[Sales Amount - Source]",
                ")"
              ]
            }
          },
          {
            "name": "Internet Sales Drillthrough - By Due Date",
            "expression": " 1",
            "isHidden": true,
            "detailRowsDefinition": {
              "expression": [
                "CALCULATETABLE",
                "(",
                "    DETAILROWS('Internet Sales'[Internet Sales Drillthrough - Default])",
                ",   USERELATIONSHIP('Internet Sales'[Due Date Key], 'Date'[Date Key])",
                ")"
              ]
            }
          },
          {
            "name": "Internet Sales Drillthrough - By Ship Date",
            "expression": " 1",
            "isHidden": true,
            "detailRowsDefinition": {
              "expression": [
                "CALCULATETABLE",
                "(",
                "    DETAILROWS('Internet Sales'[Internet Sales Drillthrough - Default])",
                ",   USERELATIONSHIP('Internet Sales'[Ship Date Key], 'Date'[Date Key])",
                ")"
              ]
            }
          },
          {
            "name": "Internet Sales Drillthrough - Date Filter Aware",
            "expression": " 1",
            "isHidden": true,
            "detailRowsDefinition": {
              "expression": [
                "VAR ",
                "    SelectedDateFilter = ",
                "        SELECTEDVALUE",
                "        (",
                "            'Date Filter'[Date To Filter]",
                "        ,   \"Order Date\" -- default",
                "        )",
                "VAR",
                "    UseOrderDate = ",
                "        FILTER",
                "        (",
                "            DETAILROWS('Internet Sales'[Internet Sales Drillthrough - Default])",
                "        ,   SelectedDateFilter = \"Order Date\"",
                "        )",
                "VAR",
                "    UseDueDate = ",
                "        FILTER",
                "        (",
                "            DETAILROWS('Internet Sales'[Internet Sales Drillthrough - By Due Date])",
                "        ,   SelectedDateFilter = \"Due Date\"",
                "        )",
                "VAR",
                "    UseShipDate = ",
                "        FILTER",
                "        (",
                "            DETAILROWS('Internet Sales'[Internet Sales Drillthrough - By Ship Date])",
                "        ,   SelectedDateFilter = \"Ship Date\"",
                "        )",
                "VAR",
                "    CombinedTables = ",
                "        UNION",
                "        (",
                "            UseOrderDate",
                "        ,   UseDueDate",
                "        ,   UseShipDate",
                "        )",
                "",
                "RETURN",
                "    CombinedTables"
              ]
            }
          }
        ]
      },
      {
        "name": "Date Filter",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Order Date",
              "expression": [
                "CALCULATE",
                "(",
                "    SELECTEDMEASURE()",
                ",   USERELATIONSHIP('Internet Sales'[Order Date Key], 'Date'[Date Key])",
                ") "
              ],
              "ordinal": 1
            },
            {
              "name": "Due Date",
              "expression": [
                "CALCULATE",
                "(",
                "    SELECTEDMEASURE()",
                ",   USERELATIONSHIP('Internet Sales'[Due Date Key], 'Date'[Date Key])",
                ") "
              ],
              "ordinal": 2
            },
            {
              "name": "Ship Date",
              "expression": [
                "CALCULATE",
                "(",
                "    SELECTEDMEASURE()",
                ",   USERELATIONSHIP('Internet Sales'[Ship Date Key], 'Date'[Date Key])",
                ") "
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Date To Filter",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "CalculationGroup 1",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "9061b661-7bb3-4087-ab76-c082c8bf8905",
        "fromTable": "Internet Sales",
        "fromColumn": "Order Date Key",
        "toTable": "Date",
        "toColumn": "Date Key"
      },
      {
        "name": "9581210a-de40-485b-ae6e-75439ca4d6c0",
        "fromTable": "Internet Sales",
        "fromColumn": "Due Date Key",
        "toTable": "Date",
        "toColumn": "Date Key",
        "isActive": false
      },
      {
        "name": "4729bf6d-1ff0-48a9-b6ce-caf55f946f12",
        "fromTable": "Internet Sales",
        "fromColumn": "Ship Date Key",
        "toTable": "Date",
        "toColumn": "Date Key",
        "isActive": false
      },
      {
        "name": "d4c86d6c-f091-48da-8293-48539bd6de9f",
        "fromTable": "Internet Sales",
        "fromColumn": "Product Key",
        "toTable": "Product",
        "toColumn": "Product Key"
      }
    ],
    "expressions": [
      {
        "name": "Source Query - Product",
        "kind": "m",
        "expression": [
          "let",
          "    Source = \"select#(tab)prd.[ProductKey]#(lf)    ,#(tab)prd.[ProductAlternateKey]#(lf)#(tab),#(tab)cat.[ProductCategoryKey]#(lf)#(tab),#(tab)cat.[EnglishProductCategoryName]#(lf)    ,#(tab)sub.[ProductSubcategoryKey]#(lf)#(tab),#(tab)sub.[EnglishProductSubcategoryName]#(lf)#(tab),#(tab)prd.[EnglishProductName]#(lf)#(tab),#(tab)prd.[ListPrice]#(lf)      #(lf)from#(tab)[AdventureWorksDW2019].[dbo].[DimProduct] prd#(lf)left outer join [AdventureWorksDW2019].[dbo].[DimProductSubcategory] sub on sub.[ProductSubcategoryKey] = prd.[ProductSubcategoryKey]#(lf)left outer join [AdventureWorksDW2019].[dbo].[DimProductCategory] cat on cat.[ProductCategoryKey] = sub.[ProductCategoryKey]#(lf);\"",
          "in",
          "    Source"
        ]
      },
      {
        "name": "Source Query - Internet Sales",
        "kind": "m",
        "expression": [
          "let",
          "    Source = \"select#(tab)[ProductKey]#(lf)    ,#(tab)[OrderDateKey]#(lf)    ,#(tab)[DueDateKey]#(lf)    ,#(tab)[ShipDateKey]#(lf)    ,#(tab)[SalesOrderNumber]#(lf)    ,#(tab)[SalesOrderLineNumber]#(lf)    ,#(tab)[OrderQuantity]#(lf)    ,#(tab)[SalesAmount]#(lf)      #(lf)from#(tab)[AdventureWorksDW2019].[dbo].[FactInternetSales]#(lf);\"",
          "in",
          "    Source"
        ]
      },
      {
        "name": "Source Query - Date",
        "kind": "m",
        "expression": [
          "let",
          "    Source = \"select#(tab)[DateKey]#(lf)    ,#(tab)[FullDateAlternateKey]#(lf)#(tab),#(tab)[CalendarYear]#(lf)#(tab),#(tab)[CalendarQuarter]#(lf)#(tab),#(tab)[MonthNumberOfYear]#(lf)#(tab),#(tab)[EnglishMonthName]    #(lf)    #(lf)from#(tab)[AdventureWorksDW2019].[dbo].[DimDate]#(lf);\"",
          "in",
          "    Source"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}